# Generated by Django 4.0.5 on 2022-12-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id_cirugia', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Cirugia')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Cirugia')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id doctor')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id_infraestructura', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Infraestructura')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Infraestructura')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoEspecifico',
            fields=[
                ('id_insumoEspecifico', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id insumo Espesifico')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Insumo Especifico')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoHumano',
            fields=[
                ('id_recursohumano', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Recurso Humano')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pabellon',
            fields=[
                ('id_pabellon', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombrePabellon', models.CharField(max_length=50, verbose_name='Nombre Pabellon')),
                ('disponible', models.CharField(default='Preparacion', max_length=50, verbose_name='disponible')),
                ('id_cirugia', models.ForeignKey(db_column='id_cirugia', on_delete=django.db.models.deletion.CASCADE, to='app.cirugia', verbose_name='Cirugia')),
                ('id_doctor', models.ForeignKey(db_column='id_doctor', on_delete=django.db.models.deletion.CASCADE, to='app.doctor', verbose_name='Doctor')),
                ('id_infraestructura', models.ManyToManyField(db_column='id_infraestructura', to='app.infraestructura', verbose_name='Infraestructura')),
                ('id_insumoEspecifico', models.ManyToManyField(db_column='id_insumoEspecifico', to='app.insumoespecifico', verbose_name='insumo Especifico')),
                ('id_recursohumano', models.ForeignKey(db_column='id_recursohumano', on_delete=django.db.models.deletion.CASCADE, to='app.recursohumano', verbose_name='Recurso Humano')),
            ],
        ),
    ]
